# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install -y valgrind
  - sudo apt-get install -y cppcheck
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd identifier/
  - make
