# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install -y valgrind
  - sudo apt-get install -y cppcheck
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd identifier/
  - make
  - export RED='\033[0;31m'
  - export NC='\033[0m' # No Color
script: 
  - echo "\n${RED}Unity tests + Address Sanitizer${NC}\n"
  - ./test_identifier.out
script: 
  - echo "\n${RED}CPPcheck${NC}\n"
  - cppcheck --enable=all src/identifier.c 
script:
  - echo "\n${RED}Valgrind${NC}\n"
  - valgrind --leak-check=full --show-leak-kinds=all ./test_identifier.out
script:
  - echo "\n${RED}Gcov check${NC}\n"
  - gcov -b identifier.gcno
